services:
  - type: web
    name: anurag-messenger-bot
    env: python
    buildCommand: apt-get update && apt-get install -y chromium-browser chromium-driver && pip install -r requirements.txt
    startCommand: python main_selenium.py
    envVars:
      - key: PORT
        value: 10000
